config/routes.rb
Rails.application.routes.draw do

  root 'vehicles#index'

  get ':type/update_models' => 'vehicles#update_models'
  get ':type/update_cities' => 'vehicles#update_cities'
  get ':type/:id/update_cities' => 'vehicles#update_cities'
  get ':type/:id/update_models' => 'vehicles#update_models'

  resources :cars, :trucks, :equips
  resources :vehicles

  

end

app/models/brand.rb
# Модель марки техники/авто
class Brand < ActiveRecord::Base
  has_many :models

  def self.get_brands(type)
    Brand.where(type: type)
  end
end

app/models/car.rb
# Модель легкового транспорта
class Car < Vehicle
  validates :engine_cap, length: { in: 1..3 }, numericality: true
  validates :body, :engine, :kpp, presence: true
  validates :drive, presence: true
end

app/models/city.rb
# Модкль города (для выбора в объявлении)
class City < ActiveRecord::Base
  belongs_to :region
end

app/models/equip.rb
# Модель техники
class Equip < Vehicle
end

app/models/model.rb
# Модель модели :) техники/авто
class Model < ActiveRecord::Base
  belongs_to :brand
end

app/models/region.rb
# Модель Региона (для выбора в объявлении)
class Region < ActiveRecord::Base
  has_many :cities
end

app/models/truck.rb
# Модель грузового транспорта
class Truck < Vehicle
  validates :engine_cap, length: { in: 1..3 }, numericality: true
  validates :engine, presence: true
end

app/models/vehicle.rb
# Общая модель, которая является корнем STI для
# моделей Car, Truck и Equip
class Vehicle < ActiveRecord::Base
  belongs_to :city
  belongs_to :region
  belongs_to :brand
  belongs_to :model
  has_many   :vehicle_images, dependent: :destroy

  validates :vehicle_type, :status, presence: true
  validates :year, length: { is: 4 }, presence: true
  validates :price, presence: true
  validate  :price_cannot_be_negative,
            :price_cannot_be_greater_999999999999
  validates :city_id, :region_id, presence: true
  validates :brand_id, :model_id, presence: true
  validates :vin_code, numericality: true

  # Блок самописных валидаций
  def price_cannot_be_negative
    return unless price.nil?
    errors.add(:price, 'can not be negative') if
        price < 0
  end

  def price_cannot_be_greater_999999999999
    return unless price.nil?
    errors.add(:price, 'is too big!') if
        price > 999_999_999_999
  end
  #######-Конец-#######

  # Процедура по удалению фотографий
  def erase_photos
    # Проверяем, есть ли у объявления фото?
    photo = self.vehicle_images.first
    return unless photo
    # Если есть, то удаляем по-одному
    self.vehicle_images.each do |p|
    # Необходимо для физ. удаления файлов
      p.photo = nil
      p.save
      p.destroy
    end
    self.save
  end

  # Переопределяем метод для правильного удаления фото
  def destroy
    erase_photos
    super
  end
end

app/models/vehicle_image.rb
# Модель для организации загрузки нескольких фото к одному
# объявлению с помошью gem'a Paperclip
class VehicleImage < ActiveRecord::Base
  belongs_to :vehicle

  Paperclip.interpolates :vehicle_id do |attachment, _style|
    attachment.instance.vehicle_id
  end

  has_attached_file :photo, styles: { normal: '600x600>', thumb: '150x150>' },
                            path: "#{Rails.root}/public/images/:vehicle_id/:style/:filename",
                            url:  '/images/:vehicle_id/:style/:filename'

  do_not_validate_attachment_file_type :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/cars_controller.rb
# Контроллер для работы объявлениями легкового транспорта
class CarsController < VehiclesController
  # Расширяем функционал специально для типа легкового транспорта
  def index
    @cars = Car.where(moderate: true).order('created_at DESC')
  end

  # Создание нового объекта легкового транспорта
  # Переопределен от родительского класса
  def new_vehicle(params)
    @car = Car.new(params)
  end

  private

  # Strong Params. Перечисляем необходимые для создания параметры
  def vehicle_params
    params.require(:car).permit(
      :vehicle_type, :body, :description, :engine, :engine_cap, :kpp,
      :vehicle_status, :price, :drive, :mileage, :vin_code, :year, :status,
      :region_id, :city_id, :brand_id, :model_id
    )
  end
end

app/controllers/equips_controller.rb
# Контроллер для работы с объявлениями техники
class EquipsController < VehiclesController
  def index
    @equips = Equip.where(moderate: true).order('created_at DESC')
  end

  def new_vehicle(params)
    @equip = Equip.new params
  end

  private

  def vehicle_params
    params.require(:equip).permit(
      :vehicle_type, :description, :status, :price, :vin_code, :year, :h_of_use,
      :region_id, :city_id, :brand_id, :model_id
    )
  end
end

app/controllers/trucks_controller.rb
# Контроллер для работы с объявлениями грузового транспорта
class TrucksController < VehiclesController
  def index
    @trucks = Truck.where(moderate: true)
  end

  def new_vehicle(params)
    @truck = Truck.new(params)
  end

  private

  def vehicle_params
    params.require(:truck).permit(
      :vehicle_type, :vin_code, :year, :engine, :engine_cap,
      :h_of_use, :status, :description, :price, :mileage,
      :region_id, :city_id, :brand_id, :model_id
    )
  end
end

app/controllers/vehicles_controller.rb
# Общий контроллер объявлений, от которого наследуются остальные
# три: [Car, Truck, Equip]controller
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  before_action :right_vehicle, only: [:show, :edit]

  def index
    # Выводим объявления независимо от их типа.
    @vehicles = Vehicle.where(moderate: true)
  end

  def show
    @photos = @vehicle.vehicle_images.all
  end

  def new
    # Создаем новый экземпляр класса без параметров
    @vehicle = new_vehicle nil
    # Получаем все марки текущего класса объявлений
    @brands = Brand.get_brands(controller_name.classify)
  end

  def edit
    # Получаем все марки текущего класса объявлений
    @brands = Brand.get_brands(controller_name.classify)
  end

  def create
    # Создаем новый экземпляр класса с параметрами, взятыми из формы
    @vehicle = new_vehicle(vehicle_params)
    respond_to do |format|
      if @vehicle.save
        # Если сохранение успешно, тогда сохраняем и приложенные фото при их наличии
        save_photos(params[:photos])
        # Переходим в созданное объявление
        format.html { redirect_to @vehicle, notice: 'Successfully created this offer!' }
      else
        # Если же нет, то рендерим заново вьюху и передаем ошибки
        @brands = Brand.get_brands(controller_name.classify)
        format.html { render controller: controller_name, action: :new, local: @brands }
      end
    end
  end

  def update
    respond_to do |format|
      # Аналогично методу create
      if @vehicle.update(vehicle_params)
        save_photos(params[:photos])
        format.html { redirect_to @vehicle, notice: 'Vehicle successfully updated.' }
      else
        @brands = Brand.get_brands(controller_name.classify)
        format.html { render controller: controller_name, action: :edit, local: @brands }
      end
    end
  end

  def destroy
    @vehicle.destroy
    # Переходим на главную страницу соответствующего типа объявлений
    redirect_to controller: controller_name, action: :index
  end

  #------- AJAX - запросы -------#
  def update_models
    @models = Model.where(brand_id: params[:brand_id])
    # Определяем тип обратившейся модели
    @type = params[:type].chomp('s')
  end

  def update_cities
    @cities = City.where(region_id: params[:region_id])
    @type = params[:type].chomp('s')
  end
  #----------- Конец ------------#

  protected

  def save_photos(photos)
    return unless photos
    # Удаляем старые фото
    @vehicle.erase_photos
    photos.each { |photo| @vehicle.vehicle_images.create(photo: photo) }
  end

  private

  # Вызываем колбэком
  def set_vehicle
    # Т.к. id у всех разные, данный метод является универсальным
    @vehicle = Vehicle.find(params[:id])
  end

  # Проверяем, верно ли составлен GET запрос из сети.
  # Т.к. у нас используется STI, возможно поялвение логической ошибки, когда одна модель использует
  # контроллер другой. В таком случае необходимо удостовериться, что названия модели и контроллера
  # соответствуют друг-другу.
  def right_vehicle
    not_found if @vehicle.type != controller_name.classify
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/equips_helper.rb
module EquipsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/cars/_form.html.erb
<%= form_for(@vehicle, html: { multipart: true } ) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2>Пожалуйста, исправьте данные ошибки:</h2>
      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>   

    <div class="form-group">
      <label class="col-sm-3 control-label" for="vehicle_region">Регион:</label>
      <div class="col-sm-4">
        <%= f.select :region_id, options_for_select(Region.all.collect {|region| [region.name, region.id]},0),{:include_blank => "Выберите регион..."}, {class: "form-control input-sm", type: "text"} %>
      </div>
    </div>

    <div style="display: none;" id="city" class="form-group">
      <label class="col-sm-3 control-label" for="vehicle_city">Город:</label>
      <div class="col-sm-4">
        <%= f.select :city_id, options_for_select({},0),{:include_blank => "Выберите город..."},{class: "form-control input-sm", type: "text"} %>
      </div>
    </div>
    
    <div class="form-group" id="model_section">
      <%= render 'shared/model_and_brand', f: f %>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="probeg">VIN/Заводской номер:</label>
      <div class="col-sm-4">
        <%= f.text_field :vin_code, class: "form-control input-sm " %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label rfield" for="car_year">Год выпуска</label>
      <div class="col-sm-4">
        <%= f.text_field :year, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="car_sost" >Состояние:</label>
      <div class="col-sm-4">
        <%= f.select :status, {},{},{class: "form-control input-sm"} do %>
          <% ["Отличное","Хорошее","Удовлетворительное","Плохое"].each do |x| -%>
            <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
       <label class="col-sm-3 control-label" for="vehicle_photos">Фото</label>
       <div class="col-sm-4">
          <%= file_field_tag "photos[]", type: :file, multiple: true %>
       </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="offer_desc">Описание</label>
      <div class="col-sm-4">
        <%= f.text_area :description, class: "form-control", cols: 50, rows: 7  %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="price">Цена:</label>
      <div class="col-sm-4">
        <%= f.text_field :price, class: "form-control input-sm" %>
      </div>
    </div>
  
    <div class="form-group">
      <label class="col-sm-3 control-label" for="car_engine">Тип двигателя:</label>
      <div class="col-sm-4">
        <%= f.select :engine, {}, {},{class: "form-control input-sm"} do %> 
          <% ["Бензин","Дизель","Гибрид","Электро","Газ"].each do |x| -%>
              <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="car_cuzov">Тип кузова:</label>
      <div class="col-sm-4">
        <%= f.select :vehicle_type, {}, {},{class: "form-control input-sm"} do %>
          <% ["Седан","Хетчбэк","Универсал","Минивэн","Пикап",
              "Фургон","Микроавтобус","Внедорожник","Кабриолет",
              "Кроссовер","Купе"].each do |x| -%>
              <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div> 

    <div class="form-group">
      <label class="col-sm-3 control-label" for="probeg">Пробег</label>
      <div class="col-sm-4">
        <%= f.text_field :mileage, class: "form-control input-sm " %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="car_kpp">Коробка:</label>
      <div class="col-sm-4">
        <%= f.select :kpp, {}, {}, {class: "form-control input-sm"} do %>
          <% ["Механика","Автомат","Вариатор","Робот"].each do |x| -%>
              <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="car_engv">Объем</label>
      <div class="col-sm-4">
        <%= f.text_field :engine_cap, class: "form-control input-sm"%>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="car_privod">Привод:</label>
      <div class="col-sm-4">
        <%= f.select :drive, {}, {},{class: "form-control input-sm"} do %>
          <% ["Передний","Задний","Полный"].each do |x| -%>
              <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit "Создать", class: "btn btn-primary"%>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/cars/_show_additional.html.erb
<tr>
    <td class="text-primary">
        Тип кузова
    </td>
    <td>
        <%= @vehicle.vehicle_type %>
    </td>
</tr>

<tr>
    <td class="text-primary">
        Пробег (км.)
    </td>
    <td>
        <%= @vehicle.mileage %>
    </td>
</tr>
<tr>
    <td class="text-primary">
        Коробка
    </td>
    <td>
        <%= @vehicle.kpp %>
    </td>
</tr>
<tr>
    <td class="text-primary">
        Двигатель
    </td>
    <td>
        <%= @vehicle.engine %>
    </td>
</tr>

<tr>
    <td class="text-primary">
        Объем двигателя (л.)
    </td>
    <td>
        <%= @vehicle.engine_cap %>
    </td>
</tr>
<tr>
    <td class="text-primary">
        Привод
    </td>
    <td>
        <%= @vehicle.drive %>
    </td>
</tr>

app/views/cars/index.html.erb
<h1>Просмотр легковых объявлений</h1>
<p> Создание нового объявления: <%= link_to 'Создать', new_car_path %>
<ul>
<% @cars.each do |car| %>
    <li> <%= car.vehicle_type %> <%= link_to 'Просмотр', car_path(car.id)%> <%= link_to 'Редакт.', edit_car_path(car.id) %> <%= link_to 'Удалить', car_path(car.id), { method: :delete } %></li>
<% end %>
</ul>

app/views/equips/_form.html.erb
<%= form_for(@vehicle, html: { multipart: true }) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2>Присутствуют следующие ошибки:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>  

   <div class="form-group">
      <label class="col-sm-3 control-label" for="vehicle_region">Регион:</label>
      <div class="col-sm-4">
        <%= f.select :region_id, options_for_select(Region.all.collect {|region| [region.name, region.id]},0),{:include_blank => "Выберите регион..."}, {class: "form-control input-sm", type: "text"} %>
      </div>
    </div>

    <div style="display: none;" id="city" class="form-group">
      <label class="col-sm-3 control-label" for="vehicle_city">Город:</label>
      <div class="col-sm-4">
        <%= f.select :city_id, options_for_select({},0),{:include_blank => "Выберите город..."},{class: "form-control input-sm", type: "text"} %>
      </div>
    </div>

    <div class="form-group" id="model_section">
      <%= render 'shared/model_and_brand', f: f %>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="vehicle_type">Тип</label>
      <div class="col-sm-4">
        <%= f.select :vehicle_type, {},{:include_blank => "Выберите тип..."},{class: "form-control input-sm"} do %>
          <% ["Медицинское","Металлообрабатывающее","Пищевое","Промышленное","Полиграфическое",
              "Сельскохозяйственное","Торговое","Упаковочное/Разливное","Энергетическое","Другое"].each do |x| -%>
              <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Год выпуска</label>
      <div class="col-sm-4">
        <%= f.number_field :year, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="probeg">VIN/Заводской номер:</label>
      <div class="col-sm-4">
        <%= f.text_field :vin_code, class: "form-control input-sm " %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Наработка(часов)</label>
      <div class="col-sm-4">
        <%= f.number_field :h_of_use, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Состояние</label>
      <div class="col-sm-4">
        <%= f.select :status, {},{},{class: "form-control input-sm"} do %>
          <% ["Отличное","Хорошее","Удовлетворительное","Плохое"].each do |x| -%>
            <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
       <label class="col-sm-3 control-label" for="vehicle_photos">Фото</label>
       <div class="col-sm-4">
          <%= file_field_tag "photos[]", type: :file, multiple: true %>
       </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="offer_desc">Описание</label>
      <div class="col-sm-4">
        <%= f.text_area :description, class: "form-control", cols: 50, rows: 7  %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="price">Цена:</label>
      <div class="col-sm-4">
        <%= f.text_field :price, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-4 col-lg-offset-2">
        <%= f.submit "Создать", class: "btn btn-primary"%>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/equips/_show_additional.html.erb
<tr>
    <td class="text-primary">
        Тип техники
    </td>
    <td>
        <%= @vehicle.vehicle_type %>
    </td>
</tr>

<tr>
    <td class="text-primary">
        Наработка (часов) 
    </td>
    <td>
        <%= @vehicle.h_of_use %>
    </td>
</tr>

app/views/equips/index.html.erb
<h1>Просмотр оборудования</h1>
<p> Создание нового объявления: <%= link_to 'Создать', new_equip_path %>
<ul>
<% @equips.each do |equip| %>
    <li> <%= equip.vehicle_type %> <%= link_to 'Просмотр', equip_path(equip.id)%> <%= link_to 'Редакт.', edit_equip_path(equip.id) %> <%= link_to 'Удалить', equip_path(equip.id), { method: :delete } %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Technohunterv2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_model_and_brand.html.erb
<label class="col-sm-3 control-label" for="vehicle_brand" >Марка:</label>
<div class="col-sm-4">
    <%= f.select :brand_id, options_for_select(@brands.collect {|brand| [brand.name, brand.id]},1), {:include_blank => "Выберите марку..."}, { class: "form-control input-sm", type: "text"} %>
</div>

<div style="display: none;" id="model" class="form-group">
    <label class="col-sm-3 control-label" for="car_model" >Модель:</label>
    <div class="col-sm-4">
        <%= f.select :model_id, options_for_select('test1', 'test2'), {:include_blank => "Выберите модель..."}, { class: "form-control input-sm"} %>
    </div>
</div>

app/views/trucks/_form.html.erb
<%= form_for(@vehicle, html: { multipart: true }) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2>Присутствуют следующие ошибки:</h2>
      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>  

   <div class="form-group">
      <label class="col-sm-3 control-label" for="vehicle_region">Регион:</label>
      <div class="col-sm-4">
        <%= f.select :region_id, options_for_select(Region.all.collect {|region| [region.name, region.id]},0),{:include_blank => "Выберите регион..."}, {class: "form-control input-sm", type: "text"} %>
      </div>
    </div>

    <div style="display: none;" id="city" class="form-group">
      <label class="col-sm-3 control-label" for="vehicle_city">Город:</label>
      <div class="col-sm-4">
        <%= f.select :city_id, options_for_select({},0),{:include_blank => "Выберите город..."},{class: "form-control input-sm", type: "text"} %>
      </div>
    </div>

    <div class="form-group" id="model_section">
      <%= render 'shared/model_and_brand', f: f %>
    </div>    

    <div class="form-group">
      <label class="col-sm-3 control-label" for="car_type">Тип авто</label>
      <div class="col-sm-4">
        <%= f.select :vehicle_type, {},{:include_blank => "Выберите тип..."},{class: "form-control input-sm"} do %>
          <% ["Автобетоносмеситель","Автобус","Автокран","Бульдозер","Буровая установка","Грузовик","Коммунальная техника",
              "Легкий транспорт","Погрузчик","Прицеп","Сельхозтехника",
              "Строительная техника","Самосвал","Техника для лесозаготовки","Тягач","Фургон",
              "Экскаватор"].each do |x| -%>
              <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Год выпуска</label>
      <div class="col-sm-4">
        <%= f.number_field :year, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="probeg">VIN/Заводской номер:</label>
      <div class="col-sm-4">
        <%= f.text_field :vin_code, class: "form-control input-sm " %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Пробег(км)</label>
      <div class="col-sm-4">
        <%= f.text_field :mileage, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Тип двигателя</label>
      <div class="col-sm-4">
        <%= f.select :engine, {},{},{class: "form-control input-sm"} do %> 
          <% ["Бензин","Дизель","Гибрид","Электро","Газ"].each do |x| -%>
              <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Объем(л)</label>
      <div class="col-sm-4">
        <%= f.text_field :engine_cap, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Наработка(часов)</label>
      <div class="col-sm-4">
        <%= f.number_field :h_of_use, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label">Состояние</label>
      <div class="col-sm-4">
        <%= f.select :status, {},{},{class: "form-control input-sm"} do %>
          <% ["Отличное","Хорошее","Удовлетворительное","Плохое"].each do |x| -%>
            <%= content_tag(:option, x) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
       <label class="col-sm-3 control-label" for="vehicle_photos">Фото</label>
       <div class="col-sm-4">
          <%= file_field_tag "photos[]", type: :file, multiple: true %>
       </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="offer_desc">Описание</label>
      <div class="col-sm-4">
        <%= f.text_area :description, class: "form-control", cols: 50, rows: 7  %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label" for="price">Цена:</label>
      <div class="col-sm-4">
        <%= f.text_field :price, class: "form-control input-sm" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-4 col-lg-offset-2">
        <%= f.submit "Создать", class: "btn btn-primary"%>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/trucks/_show_additional.html.erb
<tr>
    <td class="text-primary">
        Тип техники
    </td>
    <td>
        <%= @vehicle.vehicle_type %>
    </td>
</tr>

<tr>
    <td class="text-primary">
        Пробег (км.)
    </td>
    <td>
        <%= @vehicle.mileage %>
    </td>
</tr>
<tr>
    <td class="text-primary">
        Двигатель
    </td>
    <td>
        <%= @vehicle.engine %>
    </td>
</tr>

<tr>
    <td class="text-primary">
        Объем двигателя (л.)
    </td>
    <td>
        <%= @vehicle.engine_cap %>
    </td>
</tr>
<tr>
    <td class="text-primary">
        Наработка (часов) 
    </td>
    <td>
        <%= @vehicle.h_of_use %>
    </td>
</tr>

app/views/trucks/index.html.erb
<h1>Просмотр грузовых объявлений</h1>
<p> Создание нового объявления: <%= link_to 'Создать', new_truck_path %>
<ul>
<% @trucks.each do |truck| %>
    <li> <%= truck.vehicle_type %> <%= link_to 'Просмотр', truck_path(truck.id)%> <%= link_to 'Редакт.', edit_truck_path(truck.id) %> <%= link_to 'Удалить', truck_path(truck.id), { method: :delete } %></li>
<% end %>
</ul>

app/views/vehicles/_cities.html.erb
<option value="">Выберите город</option>
<% @cities.each do |city| %>
	<option value="<%= city.id %>"><%= city.name %></option>
<% end %>

app/views/vehicles/_models.html.erb
<option value=""> Выберите модель... </option>
<% @models.each do |model| %>
	<option value="<%= model.id %>"><%= model.name %></option>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Редактирование объявления</h1>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<h1>Рандомные предложения из БД</h1>
<% @vehicles.each do |vehicle| %>
    <li><%= vehicle.vehicle_type %></li>
<% end %>

app/views/vehicles/new.html.erb
<h1>Создание предложения</h1>

<%= render 'form' %>

app/views/vehicles/update_cities.js.erb
$("#<%= @type %>_city_id").empty()
  .append("<%= escape_javascript(render(partial: 'vehicles/cities.html.erb', local: @cities)) %>")

app/views/vehicles/update_models.js.erb
$("#<%= @type %>_model_id").empty()
  .append("<%= escape_javascript(render(partial: 'vehicles/models.html.erb', local: @models)) %>")